steps:
- task: Gradle@2
  displayName: Build core
  inputs:
    gradleWrapperFile: 'gradlew'
    options: '--no-daemon --continue'
    tasks: 'check'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'


